# LLM_Judge_Dashboard.py

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import json

# --- Page Configuration ---
st.set_page_config(page_title="LLM Judge Dashboard", page_icon="📊", layout="wide")
st.title("📊 LLM-as-a-Judge Results Dashboard")

# --- Helper Functions ---
def parse_results_file(uploaded_file):
    """Parses an uploaded JSONL file into a pandas DataFrame."""
    try:
        lines = uploaded_file.getvalue().decode('utf-8').strip().split('\n')
        data = [json.loads(line) for line in lines if line.strip()]
        df = pd.json_normalize(data)
        return df
    except Exception as e:
        st.error(f"Error parsing file: {e}. Please ensure it is a valid JSONL file.")
        return None

# --- Main App ---
st.sidebar.title("Configuration")
st.sidebar.info("Upload the `results_*.jsonl` file generated by the offline `run_evaluation.py` script to begin your analysis.")

uploaded_file = st.sidebar.file_uploader(
    "Upload Evaluation Results",
    type=['jsonl', 'json'],
    help="Upload the JSONL file containing the LLM judge's evaluations."
)

if uploaded_file is None:
    st.warning("Please upload a results file to view the dashboard.")
    st.stop()

results_df = parse_results_file(uploaded_file)

if results_df is None:
    st.stop()

st.success(f"✅ Successfully loaded and parsed {len(results_df)} evaluation results from **{uploaded_file.name}**.")

# Separate dataframes for different evaluation types for easier analysis
value_df = results_df[results_df['question_type_evaluated'] == 'value'].copy()
reasoning_df = results_df[results_df['question_type_evaluated'] == 'open_ended_reasoning'].copy()

# --- Top-Level Summary Metrics ---
st.header("📈 Overall Performance")
col1, col2, col3 = st.columns(3)
with col1:
    if 'final_verdict' in results_df.columns:
        acceptance_rate = (results_df['final_verdict'] == 'accepted').sum() / len(results_df) * 100
        st.metric("Overall Acceptance Rate", f"{acceptance_rate:.1f}%")
        st.progress(acceptance_rate / 100)
    else:
        st.metric("Overall Acceptance Rate", "N/A")
with col2:
    if 'confidence_score' in results_df.columns:
        avg_confidence = results_df['confidence_score'].mean()
        st.metric("Avg. Judge Confidence", f"{avg_confidence:.0f}%")
    else:
        st.metric("Avg. Judge Confidence", "N/A")

st.markdown("---")

# --- Charts and Visualizations ---
st.header("🔬 Detailed Analysis")
col1, col2 = st.columns(2)
with col1:
    if 'model_name' in results_df.columns and 'final_verdict' in results_df.columns:
        model_acceptance = results_df.groupby('model_name')['final_verdict'].apply(lambda x: (x == 'accepted').mean() * 100).reset_index()
        fig_model = px.bar(
            model_acceptance.sort_values(by='final_verdict', ascending=False),
            x='model_name', y='final_verdict', title="Acceptance Rate by Model",
            labels={'model_name': 'Model', 'final_verdict': 'Acceptance Rate (%)'},
            color='final_verdict', color_continuous_scale=px.colors.sequential.Greens, range_y=[0, 100]
        )
        st.plotly_chart(fig_model, use_container_width=True)
with col2:
    if 'question_type' in results_df.columns and 'final_verdict' in results_df.columns:
        type_acceptance = results_df.groupby('question_type')['final_verdict'].apply(lambda x: (x == 'accepted').mean() * 100).reset_index()
        fig_type = px.bar(
            type_acceptance.sort_values(by='final_verdict', ascending=False),
            x='question_type', y='final_verdict', title="Acceptance Rate by Question Type",
            labels={'question_type': 'Question Type', 'final_verdict': 'Acceptance Rate (%)'},
            color='final_verdict', color_continuous_scale=px.colors.sequential.Blues, range_y=[0, 100]
        )
        st.plotly_chart(fig_type, use_container_width=True)

st.markdown("#### Analysis of 'Value' Questions")
if not value_df.empty:
    verdict_counts = value_df['verdict'].value_counts()
    fig_pie = px.pie(verdict_counts, values=verdict_counts.values, names=verdict_counts.index, title="Verdict Distribution for 'Value' Questions")
    st.plotly_chart(fig_pie, use_container_width=True)
else:
    st.info("No 'value' type questions were evaluated in this dataset.")

st.markdown("#### Analysis of 'Open-Ended Reasoning' Questions")
if not reasoning_df.empty:
    avg_scores = {'Correctness': reasoning_df['scores.correctness'].mean(), 'Completeness': reasoning_df['scores.completeness'].mean(), 'Clarity': reasoning_df['scores.clarity'].mean()}
    fig_reasoning = go.Figure(data=[go.Bar(x=list(avg_scores.keys()), y=list(avg_scores.values()), text=[f"{v:.1f}" for v in avg_scores.values()], textposition='auto', marker_color=['#1f77b4', '#ff7f0e', '#2ca02c'])])
    fig_reasoning.update_layout(title="Average Scores for 'Open-Ended Reasoning' Questions", yaxis_title="Score (1-10)", yaxis_range=[0, 10])
    st.plotly_chart(fig_reasoning, use_container_width=True)
else:
    st.info("No 'open_ended_reasoning' type questions were evaluated in this dataset.")

st.markdown("---")

# --- Detailed Results Table with Filtering ---
st.header("📋 Detailed Results")
f_col1, f_col2, f_col3 = st.columns(3)
with f_col1:
    models = ['All'] + sorted(results_df['model_name'].unique().tolist())
    selected_model = st.selectbox("Filter by Model", models)
with f_col2:
    types = ['All'] + sorted(results_df['question_type'].unique().tolist())
    selected_type = st.selectbox("Filter by Question Type", types)
with f_col3:
    verdicts = ['All', 'accepted', 'rejected']
    selected_verdict = st.selectbox("Filter by Final Verdict", verdicts)

filtered_df = results_df.copy()
if selected_model != 'All': filtered_df = filtered_df[filtered_df['model_name'] == selected_model]
if selected_type != 'All': filtered_df = filtered_df[filtered_df['question_type'] == selected_type]
if selected_verdict != 'All': filtered_df = filtered_df[filtered_df['final_verdict'] == selected_verdict]

st.write(f"Showing {len(filtered_df)} of {len(results_df)} results")

for _, row in filtered_df.iterrows():
    final_verdict = row.get('final_verdict', 'N/A')
    verdict_icon = "✅" if final_verdict == 'accepted' else "❌"
    expander_title = (f"{verdict_icon} {row.get('question_id', 'N/A')} | "
                      f"Model: {row.get('model_name', 'N/A')} | "
                      f"Verdict: {final_verdict.upper()}")

    with st.expander(expander_title):
        col1, col2 = st.columns([3, 2])
        with col1:
            st.markdown(f"**Question:** _{row.get('question', '')}_")
            st.markdown("**Golden Answer:**"); st.code(row.get('golden_answer', ''), language=None)
            st.markdown("**Model Answer:**"); st.code(row.get('model_answer', ''), language=None)
        with col2:
            st.markdown(f"**Question Type:** `{row.get('question_type', 'N/A')}`")
            st.markdown(f"**Language:** `{row.get('language', 'N/A')}`") # Display language if present
            eval_type = row.get('question_type_evaluated')
            if eval_type == 'value':
                st.metric("Accuracy Score (0-3)", f"{row.get('accuracy_score', 'N/A')}")
                st.markdown(f"**Detailed Verdict:** `{row.get('verdict', 'N/A')}`")
            elif eval_type == 'open_ended_reasoning':
                st.metric("Correctness", f"{row.get('scores.correctness', 'N/A'):.1f} / 10")
                st.metric("Completeness", f"{row.get('scores.completeness', 'N/A'):.1f} / 10")
                st.metric("Clarity", f"{row.get('scores.clarity', 'N/A'):.1f} / 10")
                st.metric("Overall Score", f"{row.get('overall_score', 'N/A'):.1f} / 10")
            st.metric("Judge Confidence", f"{row.get('confidence_score', 0):.0f}%")
        st.markdown("**Judge Reasoning:**"); st.info(row.get('reasoning', 'No reasoning provided.'))